module.exports = {
  patrols: [
    {
      name: "Officer Ramesh Gowda",
      vehicleId: "KA-03-G-110",
      status: "Available",
      distance: "0.8 km",
      casesHandled: 142,
      responseTime: "8 mins",
      cleared: 138,
      points: 2840,
      badge: "Elite",
      stars: 5
    },
    {
      name: "Officer Sunita Sen",
      vehicleId: "KA-01-G-954",
      status: "On Duty",
      distance: "2.1 km",
      casesHandled: 156,
      responseTime: "11 mins",
      cleared: 151,
      points: 2410,
      badge: "Expert",
      stars: 4
    },
    {
      name: "Officer Christopher D'Souza",
      vehicleId: "KA-51-G-228",
      status: "Available",
      distance: "1.4 km",
      casesHandled: 131,
      responseTime: "9 mins",
      cleared: 129,
      points: 1980,
      badge: "Senior",
      stars: 4
    },
    {
      name: "Officer Priya Nair",
      vehicleId: "KA-09-G-881",
      status: "Available",
      distance: "3.2 km",
      casesHandled: 98,
      responseTime: "14 mins",
      cleared: 92,
      points: 1540,
      badge: "Active",
      stars: 3
    },
    {
      name: "Officer Vikram Kulkarni",
      vehicleId: "KA-04-G-221",
      status: "On Duty",
      distance: "0.6 km",
      casesHandled: 74,
      responseTime: "10 mins",
      cleared: 70,
      points: 1120,
      badge: "Active",
      stars: 3
    }
  ],
  violations: [
    {
      id: "VIO-8041",
      vehicleType: "Two-Wheeler",
      plateNumber: "KA-03-MX-8891",
      violationType: "Helmet Non Compliance",
      confidence: 0.98,
      timestamp: "2026-06-16T14:10:45Z",
      cameraId: "CAM-04",
      location: "Silk Board Junction, Outer Ring Rd",
      imagePath: "/assets/cam_helmet.png",
      status: "Pending",
      annotatedBox: { x: 120, y: 80, width: 90, height: 95 },
      explainability: "Rider head region detected without safety helmet. Bounding box maps motorcycle registration plate KA-03-MX-8891.",
      state: "Karnataka",
      owner: "Suresh Gowda",
      chassis: "ME3SKX9827B91",
      emergencyFlag: false
    },
    {
      id: "VIO-8042",
      vehicleType: "SUV",
      plateNumber: "KA-51-AB-1024",
      violationType: "Illegal Parking",
      confidence: 0.95,
      timestamp: "2026-06-16T14:09:12Z",
      cameraId: "CAM-12",
      location: "Indiranagar 100ft Rd",
      imagePath: "/assets/cam_parking.png",
      status: "Approved",
      annotatedBox: { x: 250, y: 180, width: 310, height: 160 },
      explainability: "Static white vehicle localized inside restricted polygon zone mask for over 180 seconds. Sidewalk blockage registered.",
      state: "Karnataka",
      owner: "Ankit Sharma",
      chassis: "MA1PLX8876G11",
      emergencyFlag: false
    },
    {
      id: "VIO-8043",
      vehicleType: "Two-Wheeler",
      plateNumber: "KA-01-EQ-9551",
      violationType: "Triple Riding",
      confidence: 0.96,
      timestamp: "2026-06-16T14:07:33Z",
      cameraId: "CAM-08",
      location: "Koramangala 80ft Rd",
      imagePath: "/assets/cam_triple.png",
      status: "Pending",
      annotatedBox: { x: 180, y: 110, width: 140, height: 180 },
      explainability: "Three distinct head regions localized on a single motorcycle chassis box. Exceeds load safety limit.",
      state: "Karnataka",
      owner: "Manpreet Singh",
      chassis: "MB3SKZ9281B20",
      emergencyFlag: false
    },
    {
      id: "VIO-8044",
      vehicleType: "Sedan",
      plateNumber: "KA-04-HA-2287",
      violationType: "Seatbelt Non Compliance",
      confidence: 0.94,
      timestamp: "2026-06-16T13:58:04Z",
      cameraId: "CAM-15",
      location: "MG Road, Near Metro Pillar 110",
      imagePath: "/assets/cam_parking.png",
      status: "Pending",
      annotatedBox: { x: 300, y: 150, width: 80, height: 110 },
      explainability: "Front cabin windshield crop parses rider torso without diagonal seatbelt strap placement.",
      state: "Karnataka",
      owner: "Divya Hegde",
      chassis: "MD4PAX7726H22",
      emergencyFlag: false
    },
    {
      id: "VIO-8045",
      vehicleType: "Two-Wheeler",
      plateNumber: "KA-03-MX-8891",
      violationType: "Wrong Side Driving",
      confidence: 0.91,
      timestamp: "2026-06-16T13:52:19Z",
      cameraId: "CAM-04",
      location: "Silk Board Junction, Outer Ring Rd",
      imagePath: "/assets/cam_helmet.png",
      status: "Approved",
      annotatedBox: { x: 140, y: 90, width: 100, height: 105 },
      explainability: "Directional vector flow tracking indicates vehicle moving opposite to road vector standard layout.",
      state: "Karnataka",
      owner: "Suresh Gowda",
      chassis: "ME3SKX9827B91",
      emergencyFlag: false
    },
    {
      id: "VIO-8046",
      vehicleType: "Ambulance",
      plateNumber: "KA-51-AM-9110",
      violationType: "Illegal Parking",
      confidence: 0.99,
      timestamp: "2026-06-16T13:45:00Z",
      cameraId: "CAM-21",
      location: "Majestic Crossing Corridor",
      imagePath: "/assets/cam_parking.png",
      status: "Approved",
      annotatedBox: { x: 190, y: 120, width: 120, height: 130 },
      explainability: "Emergency Vehicle (Ambulance) identified. Signal priority override issued. Alerting lanes ahead.",
      state: "Karnataka",
      owner: "BGS Global Hospital",
      chassis: "MH2EMX1102A11",
      emergencyFlag: true
    },
    {
      id: "VIO-8047",
      vehicleType: "Two-Wheeler",
      plateNumber: "KA-03-MX-8891",
      violationType: "Mobile Phone Usage While Driving",
      confidence: 0.89,
      timestamp: "2026-06-16T13:30:10Z",
      cameraId: "CAM-04",
      location: "Silk Board Junction",
      imagePath: "/assets/cam_helmet.png",
      status: "Approved",
      annotatedBox: { x: 130, y: 85, width: 95, height: 100 },
      explainability: "Rider right arm region localized next to head with phone dimensions crop identified.",
      state: "Karnataka",
      owner: "Suresh Gowda",
      chassis: "ME3SKX9827B91",
      emergencyFlag: false
    }
  ]
};
